group_name: "corr_low_n_widths"

base_params:
  batch_size: 10
  num_latents: 200
  N_E: 50
  wandb_logging: True
  feedforward_covariance_learning: False
  recurrent_covariance_learning: False
  feedforward_voltage_learning: False
  recurrent_voltage_learning: False
  initial_feedforward_weight_scaling: 1.0
  random_seed: 18
  dt: 0.01
  tau_u: 50.0
  tau_M: 1000.0
  tau_W: 2000.0
  tau_k: 4000.0
  zeta: 10.0
  T: 10000000.0
  homeostasis_target: 1.0
  homeostasis_power: 1.0
  activation_function_name: "rectified_quadratic"
  dynamics_log_time: 1000.0
  mode_log_time: 1000.0
  rate_computation_threshold: 0.0001
  rate_computation_iterations: 10000
  k_I: 25.0


param_grid:
  homeostasis: [True, False]
  N_I: [5,6,7,8,9,10,11,12,13,14,15]

  input_config:
    - type: "modulated_circular" 
      param_grid:  
        mixing_parameter: [0.2, 0.4, 0.6]
        vm_concentration: [1.0]
        density_location: [0.0]
        tuning_width: [0.25] 