group_name: "nonlinearity_experiment"

base_params:
  target_rate: 1.0
  num_latents: 200
  N_E: 100
  N_I: 100
  wandb_logging: True
  random_seed: 10
  covariance_learning: False
  initial_feedforward_weight_scaling: 1.0
  dt: 0.01
  tau_u: 50.0
  tau_M: 1000.0
  tau_W: 2000.0
  tau_k: 2000.0
  zeta: 10.0
  T: 5000000.0 
  rate_homeostasis: True
  dynamics_log_time: 1000.0
  mode_log_time: 1000.0
  rate_computation_threshold: 0.0001
  rate_computation_iterations: 10000
  k_I: 20.0

param_grid:
  variable_input_mass: [True, False]
  activation_function_name: ["rectified_linear", "rectified_powerlaw_1p5", "rectified_quadratic", "rectified_cubic"]

  input_config:
    - type: "modulated_circular" 
      param_grid:  
        mixing_parameter: [0.5]
        vm_concentration: [1.0]
        tuning_width: [0.25] 
        modulation_mixing_parameter: [0.0]
        modulation_vm_concentration: [1.0]

