group_name: "prob_modulation"

base_params:
  num_latents: 200
  N_E: 100
  N_I: 100
  wandb_logging: True
  random_seed: 10
  covariance_learning: False
  activation_function_name: "rectified_quadratic"
  initial_feedforward_weight_scaling: 1.0
  dt: 0.01
  tau_u: 50.0
  tau_M: 1000.0
  tau_W: 2000.0
  tau_k: 2000.0
  zeta: 10.0
  T: 5000000.0 
  homeostasis_target: 1.0
  dynamics_log_time: 1000.0
  mode_log_time: 1000.0
  rate_computation_threshold: 0.0001
  rate_computation_iterations: 10000
  k_I: 20.0

param_grid:
  homeostasis_type: ["rate", "none"]

  input_config:
    - type: "modulated_circular" 
      param_grid:  
        mixing_parameter: [0.15, 0.3]
        vm_concentration: [1.0]
        tuning_width: [0.25] 
        modulation_mixing_parameter: [0.15, 0.3]
        modulation_vm_concentration: [1.0]